-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgw5SZETmXWveRmDEF
C2YTRN9ISUy7boBrrhspQgDGiHKgCgYIKoZIzj0DAQehRANCAARcKinKk43JKaMN
7K+mwoycBhzx40vFmd3QylUXxHaxMpa7HvZHuT4zCK0D1Ira03LpvcitQMqbwyG5
9aJpRbWf
-----END PRIVATE KEY-----